users:
  name_length: 50
  email_length: 255
  password_length: 6
application:
  font: "https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
  font_awesome: "https://use.fontawesome.com/releases/v5.6.3/css/all.css"
