users:
  name_length: 50
  email_length: 255
  password_length: 6
  page: 30
application:
  font: "https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
  font_awesome: "https://use.fontawesome.com/releases/v5.6.3/css/all.css"
matches:
  page: 30
  max: 15
  min: 0
  value: 1
  valuemin: 90
  valueex: 0
match_results:
  page: 30
  value: 0
  min: 0
rankings:
  page: 30
teams:
  page: 30
error: "error"
success: "success"
bonus: 2
match_per: 15
seconds: 60
minhalftime: 15
leagues:
  page: 30
  value: 0
  min: 0
min_half_time: 15
